# Generated by Django 2.2 on 2020-07-30 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='评论内容')),
                ('object_id', models.PositiveIntegerField(verbose_name='表对应的数据id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='表名')),
            ],
            options={
                'verbose_name_plural': '评论详情',
                'db_table': 'comment',
                'ordering': ['-created_time'],
            },
        ),
    ]
