# Generated by Django 2.2 on 2020-08-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200805_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Comment', verbose_name='初始评论id'),
        ),
    ]
