# Generated by Django 2.2 on 2020-08-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20200805_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论详情'},
        ),
    ]
