# Generated by Django 2.2 on 2020-08-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='表对应的数据id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='表名')),
            ],
            options={
                'verbose_name_plural': '阅读记录',
                'db_table': 'read_num',
                'ordering': ['-created_time'],
            },
        ),
    ]
