# Generated by Django 2.2 on 2020-07-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_count', '0002_readnum_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='read_num',
        ),
        migrations.AlterField(
            model_name='readnum',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='表对应的数据id'),
        ),
    ]
