# Generated by Django 2.2 on 2020-07-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_count', '0003_auto_20200729_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='author',
        ),
    ]
