# Generated by Django 2.2 on 2020-07-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_count', '0004_remove_readnum_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readnum',
            options={'ordering': ['-created_time'], 'verbose_name_plural': '阅读记录'},
        ),
        migrations.AlterField(
            model_name='readnum',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='阅读时间'),
        ),
    ]
