# Generated by Django 2.2 on 2020-08-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='icon/default.jpg', null=True, upload_to='icon', verbose_name='头像'),
        ),
    ]
