# Generated by Django 2.2 on 2020-07-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_auto_20200723_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time'], 'verbose_name_plural': '博客'},
        ),
    ]
