# Generated by Django 2.2 on 2020-07-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_auto_20200728_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
    ]
